### ISSUE TITLE
no "lang" breaks karma

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-element#5]
basing elements off of this with no property `lang` defined in `static get properties` will break karma testing

**Comment by Holger-Will** [comment]
still have to figure out how to "inherit" the values from `super.properties`

**Comment by alexlemaire** [comment]
While working on the `element` automatic documentation and cleaning up code/test I found out this issue again.

As of now, when not providing `lang` as a property of every element it works fine in karma testing and the element inherit the default `lang` value from `kaskadi-element` as it should.

See 2nd test case of `kaskadi-date-icon` [here](https://github.com/kaskadi/kaskadi-date-icon/blob/master/test/basic.test.js) where I test an element without `date` or `lang` attribute provided and check if it really displays the current date in English.

Closing!
